parameters:
    demontpx_util.intl.locale: '%kernel.default_locale%'
    demontpx_util.charset: '%kernel.charset%'

services:
    _defaults:
        autowire: true

    Demontpx\UtilBundle\Slug\SlugifySlugger:
    Demontpx\UtilBundle\Slug\SluggerInterface: '@Demontpx\UtilBundle\Slug\SlugifySlugger'

    Demontpx\UtilBundle\Slug\SluggableManager:
    Demontpx\UtilBundle\Slug\SluggedUrlGenerator:

    demontpx_util.slug.slugger: '@Demontpx\UtilBundle\Slug\SluggerInterface'
    demontpx_util.slug.sluggable_manager: '@Demontpx\UtilBundle\Slug\SluggableManager'
    demontpx_util.slug.slugged_url_generator: '@Demontpx\UtilBundle\Slug\SluggedUrlGenerator'

    Demontpx\UtilBundle\Intl\SimpleDateFormatter:

    Demontpx\UtilBundle\Twig\SlugExtension:
        tags: [twig.extension]

    Demontpx\UtilBundle\Text\TextTruncater:
        arguments:
            - '%demontpx_util.charset%'

    demontpx_util.text.truncater: '@Demontpx\UtilBundle\Text\TextTruncater'

    Demontpx\UtilBundle\Twig\TextExtension:
        tags: [twig.extension]

    Demontpx\UtilBundle\Twig\SimpleDateFormatterExtension:
        tags: [twig.extension]

    Demontpx\UtilBundle\Twig\DateShortExtension:
        tags: [twig.extension]
